# Generated by Django 3.1.5 on 2021-02-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0009_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
